lession8/HelloWorld/HelloWorld/HelloWorld/Models/ErrorViewModel.cs
using System;

namespace HelloWorld.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lession8/HelloWorld/HelloWorld/HelloWorld/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloWorld.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string Fullname { get; set; }
        public string Gender { get; set; }
        public DateTime Dob { get; set; }
    }
}

lession8/HelloWorld/HelloWorld/HelloWorld/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloWorld.Models
{
    public class Teacher
    {
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string Gender { get; set; }
        public string Adress { get; set; }


    }

}

lession8/HelloWorld/HelloWorld/HelloWorld/Controllers/HomeController.cs
using HelloWorld.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace HelloWorld.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lession8/HelloWorld/HelloWorld/HelloWorld/Controllers/StudentController.cs
using HelloWorld.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloWorld.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            //ViewBag.StudentId = id;
            //ViewData["StudentId"] = id;

            var students = new List<Student>();
            var std1 = new Student()
            {
                StudentId = 1,
                Fullname = "Khoa Nguyen",
                Dob = DateTime.Parse("2000-10-10"),
                Gender = "Male"
            };
            var std2 = new Student()
            {
                StudentId = 2,
                Fullname = "Nam Thu",
                Dob = DateTime.Parse("2000-10-10"),
                Gender = "Male"
            };
            var std3 = new Student()
            {
                StudentId = 3,
                Fullname = "Huy Thu",
                Dob = DateTime.Parse("2000-10-10"),
                Gender = "Male"
            };
            students.Add(std1);
            students.Add(std2);
            students.Add(std3);
            return View("~/Views/Student/Student.cshtml", students);
        }

        //Attribute routing
        //[Route("/Student/Detail/{stdId}/{fn}")]
        public IActionResult Detail(int stdId, string fn)
        {
            var studentDetail = new StudentDetail()
            {
                Fullname = fn,
                StudentId = stdId
            };
            return View(studentDetail);
        }
    }

    public class StudentDetail
    {
        public int StudentId { get; set; }
        public string Fullname { get; set; }
    }
}

lession8/HelloWorld/HelloWorld/HelloWorld/Controllers/TeacherController.cs
using HelloWorld.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelloWorld.Controllers
{
    public class TeacherController : Controller
    {
        List<Teacher> teachers = new List<Teacher>();
       
        public IActionResult Index()
        {
            var teach1 = new Teacher()
            {
                TeacherId = 1,
                TeacherName = "Thi",
                Gender = "Nữ",
                Adress = "Huế"
            };

            var teach2 = new Teacher()
            {
                TeacherId = 2,
                TeacherName = "Nguyên",
                Gender = "Nam",
                Adress = "Huế"
            };
            teachers.Add(teach1);
            teachers.Add(teach2);
            return View(teachers);
        }

    }
}

lession8/HelloWorld/HelloWorld/HelloWorld/Views/Student/Detail.cshtml
@model HelloWorld.Controllers.StudentDetail
@{
}

<h1>Info of Student</h1>
<h1>StudentID = @Model.StudentId</h1>
<h1>Fullname = @Model.Fullname</h1>

lession8/HelloWorld/HelloWorld/HelloWorld/Views/Student/Student.cshtml
@using System.Collections.Generic;
@model List<Student>
    @{
        ViewData["Title"] = "Student Page";
        //Layout = "~/Views/Shared/_Layout2.cshtml";
    }

    @*<h1>Student -> Index -> @ViewData["StudentId"]</h1>*@
    @foreach(var std in Model){
<div>
    <h1>StudentId: @std.StudentId</h1>
    <h1>Fullname: @std.Fullname</h1>
    <h1>Gender: @std.Gender</h1>
    <h1>Dob: @std.Dob</h1>
    @*<a href="/Student/Detail/@std.StudentId" class="btn btn-secondary">Detail</a>*@
    <a asp-controller="Student" asp-action="Detail" asp-route-stdId="@std.StudentId" asp-route-fn="@std.Fullname" class="btn btn-secondary">Detail</a>
    <hr />
</div>
    }

lession8/HelloWorld/HelloWorld/HelloWorld/Views/Teacher/Detail.cshtml
@model HelloWorld.Models.Teacher
@{
    <h1>ID:@Model.TeacherId</h1>
    <h1>Name:@Model.TeacherName</h1>
}

lession8/HelloWorld/HelloWorld/HelloWorld/Views/Teacher/Index.cshtml
@using System.Collections.Generic;
@model List<Teacher>
@{
    ViewData["Title"] = "Teacher Page";
}
@{

    @foreach (var tch in Model)
    { 
        <div>
            <h2>ID: @tch.TeacherId</h2>
            <h2>Name: @tch.TeacherName  </h2>
            <h2>Gender: @tch.Gender</h2>
            <h2>Adress: @tch.Adress</h2>
        </div>
        <a asp-controller="Teacher" asp-action="Detail">View Detail</a>
    }
}