lession8/TimeZone/TimeZone/Models/Bank.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TimeZone.Models
{
    public class Bank
    {
        public double InventmentAmount { get; set; }
        public double YearlyInterestRate { get; set; }
        public double NumberOfYear { get; set; }
        public double InterestAmount { get; set; }
    }
}

lession8/TimeZone/TimeZone/Models/Caculators.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TimeZone.Models
{
    public class Caculators
    {
        public double NumberA { get; set; }
        public double NumberB { get; set; }
        public double NumberResult { get; set; }
    }
}

lession8/TimeZone/TimeZone/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TimeZone.Models
{
    public class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeeAdress { get; set; }
    }
}

lession8/TimeZone/TimeZone/Models/ErrorViewModel.cs
using System;

namespace TimeZone.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lession8/TimeZone/TimeZone/Models/USDToVN.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TimeZone.Models
{
    public class USDToVN
    {
        [Required(ErrorMessage = "rate is not null")]
        public int rate { get; set; }

        [Required(ErrorMessage ="USD is not null")]
        public int USD { get; set; }
        public int VND { get; set; }
    }
}

lession8/TimeZone/TimeZone/Controllers/CaculatorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeZone.Models;

namespace TimeZone.Controllers
{
    public class CaculatorController : Controller
    {

        [HttpGet]
        public IActionResult CaculatorResult()
        {
            return View(new Caculators());
        }

        [HttpPost]
        public IActionResult CaculatorResult(Caculators model, string word)
        {
            if(word == "add")
            {
                model.NumberResult = model.NumberA + model.NumberB;
            }
            if(word == "sub")
            {
                model.NumberResult = model.NumberA - model.NumberB;
            }
            if(word == "mul")
            {
                model.NumberResult = model.NumberA * model.NumberB;
            }
            if(word == "div")
            {
                model.NumberResult = model.NumberA / model.NumberB;
            }
            return View(model);
        }
    }
}

lession8/TimeZone/TimeZone/Controllers/ChangeUSDController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeZone.Models;

namespace TimeZone.Controllers
{
    public class ChangeUSDController : Controller
    {
        [HttpGet]
        public IActionResult Change()
        {
            return View(new USDToVN());
        }

        [HttpPost]
        public IActionResult Change(USDToVN model)
        {
            if(ModelState.IsValid)
            {
                model.VND = model.rate * model.USD;
            }
            return View(model);
        }
    }
}

lession8/TimeZone/TimeZone/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeZone.Models;
using TimeZone.Services;

namespace TimeZone.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeServices employeeSer;
        public EmployeeController(IEmployeeServices employeeServices)
        {
            this.employeeSer = employeeServices;
        }
        public IActionResult Show()
        {
            return View(employeeSer.Gets());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                employeeSer.Create(employee);
                return RedirectToAction("Show");
            }
            return View();
        }

    }
}

lession8/TimeZone/TimeZone/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TimeZone.Models;

namespace TimeZone.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lession8/TimeZone/TimeZone/Controllers/InterestBankController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimeZone.Models;

namespace TimeZone.Controllers
{
    public class InterestBankController : Controller
    {
        [HttpGet]
        public IActionResult Interest()
        {
            return View(new Bank());
        }
        [HttpPost]
        public IActionResult Interest(Bank model)
        {
            model.InterestAmount =  model.InventmentAmount * (model.YearlyInterestRate/100)/12 * model.NumberOfYear;
            return View("~/Views/InterestBank/hello.cshtml",model);
        }
    }
}

lession8/TimeZone/TimeZone/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TimeZone.Models;

namespace TimeZone.Controllers
{
    public class TimeController : Controller
    {
        [HttpGet("/clock")]
        public IActionResult GetTime()
        {
            DateTime date = DateTime.Now;
            return View(date);
        }

        [HttpGet("/worldclock")]
        public IActionResult GetTimeByTimezone(string timezone)
        {
            DateTime date = DateTime.Now;
            DateTime destinationDate = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(date, timezone);
            return View(destinationDate);
        }
    }
}

lession8/TimeZone/TimeZone/Views/Caculator/CaculatorResult.cshtml
@model Caculators
@{
    ViewData["Title"] = "Caculator";
}
<form asp-controller="Caculator" asp-action="CaculatorResult" method="post">
    <div class="row">
        <div class="form-group col-sm-4">
            <label asp-for="NumberA"></label>
            <input asp-for="NumberA" class="form-control" value="@Model.NumberA" />
            <span asp-validation-for="NumberA" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-4">
            <label asp-for="NumberB"></label>
            <input asp-for="NumberB" class="form-control" value="@Model.NumberB" />
            <span asp-validation-for="NumberB" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-4">
            <label asp-for="NumberResult"></label>
            <input asp-for="NumberResult" class="form-control" readonly value="@Model.NumberResult" />
        </div>
    </div>
    <div class="row">
        <div class="form-group col-sm-3">
            <button type="submit" name="word" value="add" class="form-control btn btn-danger">ADD (+)</button>
        </div>
        <div class="form-group col-sm-3">
            <button type="submit" name="word" value="sub" class="form-control btn btn-danger">SUP (-)</button>
        </div>
        <div class="form-group col-sm-3">
            <button type="submit" name="word" value="mul" class="form-control btn btn-danger">MUL (*)</button>
        </div>
        <div class="form-group col-sm-3">
            <button type="submit" name="word" value="div" class="form-control btn btn-danger">DIV (/)</button>
        </div>
    </div>
</form>

lession8/TimeZone/TimeZone/Views/ChangeUSD/Change.cshtml
@model USDToVN
@{
    ViewData["Title"] = "Change Money";
}
<form asp-controller="ChangeUSD" asp-action="Change" method="post">
    <div class="row">
        <div class="form-group col-sm-4">
            <label asp-for="rate"></label>
            <input asp-for="rate" class="form-control" value="@Model.rate" />
            <span asp-validation-for="rate" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-4">
            <label asp-for="USD"></label>
            <input asp-for="USD" class="form-control" value="@Model.USD" />
            <span asp-validation-for="USD" class="text-danger"></span>
        </div>
        <div class="form-group col-sm-4">
            <label asp-for="VND"></label>
            <input asp-for="VND" class="form-control" readonly value="@Model.VND" />
        </div>
    </div>
    <div class="row">
        <button type="submit" class="btn btn-danger">Change</button>
    </div>
</form>

lession8/TimeZone/TimeZone/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>